#!/usr/bin/env bash
#good prgramming languege
hour=0
minutes=1
while [ $hour -ne 13 ]
do
echo "Hour: $hour"
((Hour++)) 
     while [ $minutes -ne 60 ]
      do 
       echo "$minutes"
             ((minutes++))
    done
((minutes=1))
done
