#!/usr/bin/env bash
#good prgramming languege
hour=0
minutes=1
while [ $hour -le 12 ]
do
echo "Hour: $hour"
((Hour++)) 
while [ $minutes -le 59 ]
do 
echo "$minutes"
((minutes++))
done
((minutes=1))
done
