#!/usr/bin/env bash
#not empty
name=school
if [ -e $name ]; then
    echo "school file exist"
else
    echo "school file doesn't exist"
exit 1
fi
if [ ! -s $name ]; then
    echo "school file is not empty"
else
    echo "school file is empty"
fi
if [ -f $name ]; then
   echo "school file is a regular file"
fi
