#!/usr/bin/env bash
#goooo
trap "I hate the kill command;quitting" SIGTERM
trap "'Y U no love me?!'" SIGINT
trap quitting SIGQUIT
echo $$ > /var/run/myscript.pid
while ((1))
do 
echo "To infinity and beyond"
((++i))
sleep 2
done
quitting(){
rm /var/run/myscript.pid
}

