#!/usr/bin/env bash
#goooo
trap "I hate the kill command;quitting" SIGTERM
trap "'Y U no love me?!'" SIGINT
trap quitting SIGQUIT
echo $$ > /var/run/myscript.pid
while ((1))
do 
echo "To infinity and beyond"
done
function quitting(){
rm /var/run/myscript.pid
exit
}

